name: Build Wheels

on:
  workflow_dispatch:

jobs:
  python-ci:
    if: github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/tags')
    uses: ./.github/workflows/python_ci.yaml

  build_matrix:
    strategy:
      matrix:
        python_version: [3.9, 3.11]
        platform: [manylinux_2_17_x86_64, win_amd64]

    name: Build Python ${{ matrix.python_version }} ${{ matrix.platform }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get build metadata
        id: metadata
        run: |
          export ARTIFACT_NAME=sift_stack_py-${{ github.ref_name }}-py${{ matrix.python_version }}-${{ matrix.platform }}
          echo "artifact_name=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Pip install
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Compile requirements
        working-directory: python
        run: |
          pip-compile pyproject.toml --output-file requirements.txt

      - name: Build
        working-directory: python
        run: |
          export PLATFORM=win_amd64
          pip download -r requirements.txt -d dist --platform=${{ matrix.platform }} --only-binary=:all: --python-version=${{ matrix.python_version }}
          python setup.py bdist_wheel
          zip ${{ steps.metadata.outputs.artifact_name }}.zip dist -r
          sha1sum ${{ steps.metadata.outputs.artifact_name }}.zip | cut -f1 -d' ' > ${{ steps.metadata.outputs.artifact_name }}.sha1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.metadata.outputs.artifact_name }}
          path: |
            python/${{ steps.metadata.outputs.artifact_name }}.zip
            python/${{ steps.metadata.outputs.artifact_name }}.sha1

